### ISSUE TITLE
error querying concatenated gzip file

### ISSUE THREAD

**Issue by renevoorburg** [mattgodbolt/zindex#30]
Hi,

When I query a concatenated gzip file for multiple lines I get an error. 

This works as expected:

echo -en "line 1\nline 2\n" | gzip > lines.gz
zindex lines.gz --regex 'line ([0-9]+)' --numeric --unique

zindex/build/Release/zq lines.gz 1 2
line 1
line 2

This gives an error:

echo "line 1" | gzip > concat.gz
echo "line 2" | gzip >> concat.gz
zindex concat.gz --regex 'line ([0-9]+)' --numeric --unique

zq concat.gz 1 
line 1
zq concat.gz 2
line 2
zq concat.gz 1 2
line 1
ERROR: Error from zlib : data error

For now I am happy it even indexes concatenated gzip files. Thanks!
René

**Comment by mattgodbolt** [comment]
Thanks for the report! I'll take a look.

**Comment by renevoorburg** [comment]
Another issue that is probably related:

echo "line 1" | gzip > concat.gz
echo "line 2" | gzip >> concat.gz
echo "line 1" | gzip >> concat.gz
zindex concat.gz --regex 'line ([0-9]+)' --numeric --unique

>> ERROR: Failed to index line 3: 'line 1' - Error handling index match '1' - constraint failed

Again, this only happens for concatenated gzip files.

Thanks!

**Comment by renevoorburg** [comment]
Hi Matt,

Another issue that is probably related:

echo "line 1" | gzip > concat.gz
echo "line 2" | gzip >> concat.gz
echo "line 1" | gzip >> concat.gz
zindex concat.gz --regex 'line ([0-9]+)' --numeric --unique

ERROR: Failed to index line 3: 'line 1' - Error handling index match '1' - constraint failed
Again, this only happens for concatenated gzip files.

Thanks!
René

**Comment by mattgodbolt** [comment]
This is now actually fixed in d338361d57feab864fb45b821d05e8d2bfa9e6c8 - I've separated the other issue creating the index in the first place to another bug.
